### ISSUE TITLE
client update may be broken

### ISSUE THREAD

**Issue by peterbecich** [kubernetes-client/haskell#100]
On my machine, using the latest commit of https://github.com/kubernetes-client/gen,
the client update produces this error:
```
$ ${GEN_REPO_BASE}/openapi/haskell.sh kubernetes settings
.
.
.
 => => naming to docker.io/library/kubernetes-haskell-http-client-client-gen-with-openapi-generator:v1     0.0s
--- Running generator inside container...
/source/openapi-generator /
/
--- Downloading and pre-processing OpenAPI spec
/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py:842: 
InsecureRequestWarning: Unverified HTTPS request is being made. 
Adding certificate verification is strongly advised. 
See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn((
Traceback (most recent call last):
  File "//preprocess_spec.py", line 549, in <module>
    sys.exit(main())
  File "//preprocess_spec.py", line 538, in main
    write_json(unprocessed_spec, in_spec)
  File "//preprocess_spec.py", line 490, in write_json
    with open(filename, 'w') as out:
PermissionError: [Errno 13] Permission denied: '/output_dir/swagger.json.unprocessed'
```

Using a commit of `kubernetes-client/gen` prior to https://github.com/kubernetes-client/gen/commit/b32dcd6dc9c1c0c4fcf227c9539ae9ff0530b936 results in a different error:
```
 => => naming to docker.io/library/kubernetes-haskell-http-client-client-gen-with-openapi-generator:v1                                                                 0.0s
--- Running generator inside container...
/source/openapi-generator /
fatal: detected dubious ownership in repository at '/source/openapi-generator'
To add an exception for this directory, call:

        git config --global --add safe.directory /source/openapi-generator
```

**Comment by jonschoning** [comment]
From kubernetes-client/haskell @ https://github.com/kubernetes-client/haskell/commit/56bed0844dcbe710f9b64e66592d5e17f62e4632 , Ran `../kubernetes-client-gen/openapi/haskell.sh kubernetes settings` @ https://github.com/kubernetes-client/gen/commit/d2dd5e9f6f9c372a5220ab812146c2650c4d5367 without any issues
